# Generated by Django 4.1.3 on 2023-03-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reportealergenos',
            constraint=models.UniqueConstraint(fields=('usuario', 'producto'), name='unique_usuario_producto'),
        ),
    ]
