# Generated by Django 4.1.5 on 2023-03-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='recetaDiaria',
            field=models.BooleanField(null=True),
        ),
    ]
