# Generated by Django 3.0.5 on 2023-03-06 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alergeno',
            name='imagen',
            field=models.URLField(blank=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
