# Generated by Django 4.1.3 on 2023-03-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_alter_recetasdesbloqueadasusuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
