# Generated by Django 4.1.3 on 2023-03-19 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_reportealergenos_unique_usuario_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportealergenos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 18, 45, 34, 74246)),
        ),
    ]
