# Generated by Django 4.1.7 on 2023-03-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_alergeno_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ingredientes',
            field=models.CharField(max_length=2500),
        ),
    ]
