# Generated by Django 4.1.3 on 2023-03-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_alter_user_recetadiaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.TextField(max_length=100),
        ),
    ]
