# Generated by Django 4.1.3 on 2023-03-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0003_alter_valoracion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracion',
            name='comentario',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
