# Generated by Django 4.1.7 on 2023-03-20 18:14

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0003_alter_producto_nombre_alter_receta_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='imagen',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 300], upload_to='recetas'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='descripcion',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='receta',
            name='tiempoPreparacion',
            field=models.TextField(max_length=70),
        ),
    ]
