# Generated by Django 4.1.7 on 2023-03-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_receta_imagen_alter_receta_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='recetaDiaria',
            field=models.DateField(null=True),
        ),
    ]
