# Generated by Django 4.1.7 on 2023-03-20 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0005_alter_user_recetadiaria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recetasdesbloqueadasusuario',
            name='disponible',
        ),
    ]
